version: '3'

services:
    app:
        build: .
        container_name: api-sell-app
        volumes:
            - ./src:/var/www/api-sell/src
        ports:
            - 3000:3000

    db:
        image: mysql
        container_name: api-sell-db
        ports:
            - 3306:3306
        volumes:
            - .docker/database-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root

    db-admin:
        image: phpmyadmin
        container_name: api-sell-db-admin
        ports:
            - 8080:80
        environment:
            - PMA_HOST=api-sell-db
            - PMA_PORT=3306
